services:
  ubuntu-ssh:
    image: ubuntu:latest
    container_name: ubuntu-ssh
    ports:
      - "2222:22"
    environment:
      - USER_PASSWORD=-
    volumes:
      - .:/home/test_deploy/automatizaciones
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: >
      bash -c "apt update && apt install -y openssh-server 
      && mkdir -p /var/run/sshd 
      && echo 'root:tu_password_aqui' | chpasswd 
      && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config 
      && /usr/sbin/sshd -D"
    networks:
      - red-ubuntuSSH

networks:
  red-ubuntuSSH:
    driver: bridge
